spring:
    application:
        name: NovaRideSocketService

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

    instance:
        preferIpAddress: true